# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cutEveryPolygonRcpp <- function(x, y, group, numberOfIterations = 1L, useCentroid = TRUE) {
    .Call(`_artKIT_cutEveryPolygonRcpp`, x, y, group, numberOfIterations, useCentroid)
}

cutEveryPolygonReturnAllRcpp <- function(x, y, group, numberOfIterations = 1L, useCentroid = TRUE) {
    .Call(`_artKIT_cutEveryPolygonReturnAllRcpp`, x, y, group, numberOfIterations, useCentroid)
}

